"""
Baseline Evaluation and Debugging Utilities for JAX Tree Inference.

This module provides tools to validate and debug predictions generated by a
JAX-based tree inference pipeline against a reference XGBoost model.

It includes:
    - A baseline evaluator class for numerical consistency checks
    - Error metrics computation (max and mean absolute error)
    - Support for both single-tree and full-forest validation
    - Tree-level debugging utilities to isolate faulty trees

The evaluation workflow:
    1. Load a pretrained XGBoost model
    2. Generate baseline predictions using the original model
    3. Compare them with predictions from a JAX-compiled inference function
    4. Quantify divergence using numerical error metrics
    5. Optionally debug individual trees when mismatches occur

This module is intended for:
    - Verifying correctness of custom inference kernels
    - Debugging discrepancies in tree-based model implementations
    - Supporting research in compiler-optimized inference (e.g., XLA)

Design considerations:
    - Ensures compatibility between NumPy (XGBoost) and JAX pipelines
    - Maintains numerical stability through tolerance-based comparisons
    - Provides interpretable debugging outputs for tree-level inspection
"""

import os
import xgboost as xgb
import jax.numpy as jnp
from typing import Optional, Dict
import numpy as np

class BaseLineEvaluator:
    """
    Evaluate and validate JAX-based forest predictions against a pretrained XGBoost model.

    This class serves as a bridge between:
        - A reference XGBoost model (ground truth)
        - A custom JAX-based inference function

    It provides methods to:
        - Load and manage the baseline model
        - Compare predictions across implementations
        - Compute numerical error metrics
        - Debug inconsistencies at the tree level

    Attributes:
        pretrained_model_path (str):
            Path to the directory containing the trained XGBoost model.

        jax_predict_fn (Callable):
            Function that performs inference using JAX.

        model (xgb.XGBRegressor):
            Loaded XGBoost model used as baseline.

        model_base_score (float):
            Base score (intercept) used by the XGBoost model.
    """
    def __init__(self, jax_predict_fn, pretrained_model_path: Optional[str] = "checkpoints/xgboost_model"):
        """
        Initialize and load the pretrained XGBoost model.

        This method:
            - Instantiates an XGBoost regressor
            - Loads the trained model from disk
            - Extracts the base score used for prediction correction

        The base score is required to align JAX predictions with XGBoost outputs,
        as tree outputs are typically additive offsets to this base value.

        Notes:
            - Assumes the model is a regressor.
            - Base score extraction may require adjustment for other model types.
        """
        self.pretrained_model_path = pretrained_model_path
        self.jax_predict_fn = jax_predict_fn
        self.model = None
        self.model_base_score = None
        self.__init_model()

    def __init_model(self):
        self.model = xgb.XGBRegressor()
        self.model.load_model(os.path.join(self.pretrained_model_path, "xgboost_model.json"))
        # FIXME: as the model taken currently is Regressor so its ok to take first index for base score
        self.model_base_score = self.model.__dict__['base_score'][0]

    def check(self, X_sample, jax_params, single_tree: Optional[bool] = True, atol=1e-5):
        """
        Compare JAX predictions with baseline XGBoost predictions.

        This method evaluates the numerical consistency between:
            - Predictions from the pretrained XGBoost model
            - Predictions from the provided JAX inference function

        It supports both:
            - Single-tree evaluation (for debugging)
            - Full-forest evaluation (for end-to-end validation)

        Args:
            X_sample (array-like):
                Input samples for evaluation (NumPy or JAX array).

            jax_params (Dict):
                Dictionary containing JAX-compatible model parameters
                (features, thresholds, children indices, etc.).

            single_tree (Optional[bool], optional):
                If True, evaluates only the first tree.
                If False, evaluates the full ensemble.
                Defaults to True.

            atol (float, optional):
                Absolute tolerance for floating-point comparison.
                Defaults to 1e-5.

        Returns:
            Dict:
                A dictionary containing:
                    - is_consistent (bool): Whether predictions match within tolerance
                    - max_error (float): Maximum absolute error
                    - mean_error (float): Mean absolute error
                    - xgb_sample_output (array): Sample baseline predictions
                    - jax_sample_output (array): Sample JAX predictions

        Outputs:
            Prints:
                - Baseline and JAX predictions
                - Consistency status
                - Error statistics

        Notes:
            - JAX predictions are adjusted using the model base score.
            - Uses maximum absolute error as the primary consistency metric.
        """
        xgb_preds = None
        # baseline XGBoost model expects NumPy/Pandas form
        X_np = np.array(X_sample)
        # ----- testing -------
        if single_tree:
            booster = self.model.get_booster()
            xgb_preds = booster.predict(xgb.DMatrix(X_np), iteration_range=(0, 1), output_margin=True)
        else:
            xgb_preds = self.model.predict(X_np)
        print(f"predictions from baseline xgboost mode --- {xgb_preds}")
        # now we try taking predictions from jaxified
        jax_preds = self.jax_predict_fn(X_sample, single_tree_inference=single_tree, **jax_params)
        # add in the computation for correct value to be matched with xgboost model
        jax_corrected_preds = self.model_base_score + jax_preds
        # if single_tree:
        #     jax_corrected_preds = self.model_base_score + jax_preds
        # else:
        #     jax_corrected_preds = jax_preds
        print(f"predictions from jaxified xgboost mode --- {jax_corrected_preds}")
        # lets calculate divergence with Maximum Absolute Error (MaxAE)
        diff = jnp.abs(xgb_preds - jax_corrected_preds)
        max_error = jnp.max(diff)
        mean_error = jnp.mean(diff)
        # check around tolerance
        is_consistent = max_error < atol

        status = "CONSISTENT" if is_consistent else "MISMATCH"
        print(f"[{status}] Max Error: {max_error:.2e}")
        
        if not is_consistent:
            print(f"XGB Sample: {xgb_preds[:2]}")
            print(f"JAX Sample: {jax_corrected_preds[:2]}")

        return {
            "is_consistent": bool(is_consistent),
            "max_error": float(max_error),
            "mean_error": float(mean_error),
            "xgb_sample_output": xgb_preds[:5],
            "jax_sample_output": jax_corrected_preds[:5]
        }
    
    @staticmethod
    def debug_trees(sample_batch: jnp.array, jax_params: Dict, jax_wrapper, model = None, tree_id: Optional[int] = None):
        """
    Debug inconsistencies at the individual tree level.

    This utility isolates and evaluates each tree in the ensemble to identify
    which tree is responsible for prediction mismatches between JAX and XGBoost.

    For each tree:
        - Extracts tree-specific parameters from the full model
        - Computes baseline output using XGBoost
        - Computes JAX output using the provided wrapper
        - Measures the maximum absolute error

    If a mismatch exceeds a threshold:
        - Reports the problematic tree index
        - Prints internal tree parameters for inspection
        - Triggers a debugging breakpoint

    Args:
        sample_batch (jnp.ndarray):
            Batch of input samples used for evaluation.

        jax_params (Dict):
            Full set of JAX model parameters.

        jax_wrapper (Callable):
            Wrapper function to perform JAX inference.

        model (Optional[xgb.XGBRegressor], optional):
            Baseline XGBoost model used for comparison.

        tree_id (Optional[int], optional):
            Specific tree index to debug.
            If None, all trees are evaluated.

    Outputs:
        Prints:
            - Per-tree error metrics
            - Detailed information for mismatched trees

    Notes:
        - Uses raw tree outputs (no base score) for precise comparison.
        - Intended for deep debugging of model parsing or inference logic.
    """
        tree_range = [tree_id] if tree_id is not None else jax_params['features'].shape[0]
        for i in range(tree_range):
            # next we select the ith tree slicing so we  get the data for that from our jax 2d arrays
            current_tree_params = {
                'features': jax_params['features'][i:i+1],      # Shape [1, max_nodes]
                'thresholds': jax_params['thresholds'][i:i+1],
                'left_children': jax_params['left_children'][i:i+1],
                'right_children': jax_params['right_children'][i:i+1],
                'max_depth': jax_params['max_depth'],
                'base_score': 0.0, # We use 0.0 to see the raw tree output without the intercept
                'learning_rate': 1.0
            }
            
            # let fetch the correct output from scikit learn baseline trained model 
            booster = model.get_booster()
            xgb_tree_output = booster.predict(xgb.DMatrix(np.array(sample_batch)), iteration_range=(i, i+1), output_margin=True)
            # get jax results
            jax_tree_output = jax_wrapper(sample_batch, single_tree_inference=False, **current_tree_params)
            # lets check which tree got us wrong if any
            error = jnp.abs(xgb_tree_output - jax_tree_output).max()
            print(f"Tree {i} | Max Error: {error:.2e}")
            if error > 1e-4:
                print(f"FOUND: Tree {i} is the broken one!")
                # lets debug the exact parameters of this specific tree to see what's wrong
                print(f"Features array: {current_tree_params['features']}")
                print(f"Thresholds array: {current_tree_params['thresholds']}")
                print(f"Left Children: {current_tree_params['left_children']}")
                print(f"Right Children: {current_tree_params['right_children']}")
                # FIXME: this needs to checked later
                breakpoint()
                break
        
        
